source $VIMRUNTIME/defaults.vim

function! s:LoadScriptsFrom(directory)
  let l:directory = fnamemodify(a:directory, ':p')

  if isdirectory(l:directory)
    let s:scripts = globpath(l:directory, '*.vim', 0, 1)

    for script in s:scripts
      execute 'source' script
    endfor
  endif
endfunction

call plug#begin()
call s:LoadScriptsFrom('~/.vim')
call plug#end()

doautocmd User VimLoaded