test -s ~/.alias && . ~/.alias || true

bash_init() {

  load_scripts_from() {
    local directory="$1"

    if [ -d "$directory" ]; then
      for script in $(ls "$directory"/*.sh); do
        source $script
      done
    fi
  }

  load_scripts_from "$HOME/.bashrc.d"
}

bash_init